<?php
/**
 * 设计模式  适配器模式
 */

class Source {

    public function effect(){
        echo 'this is effect from source';
    }
}

interface TargetTable{

    public function effect();

    public function effect1();
}

// 类适配器
class Adapter extends Source implements TargetTable{

    public function effect1()
    {
        // TODO: Implement effect1() method.
    }
}


$adater = new Adapter();

$adater->effect();
$adater->effect1();

// 对象适配器
class Wrapper extends Source implements TargetTable{
    private $source;
    public function __construct($source)
    {
        $this->source = $source;
    }

    public function effect1(){
        echo 'effect1';
    }

    public function effect()
    {
        $this->source->effect(); // TODO: Change the autogenerated stub
    }
}

$adater = new Wrapper();

$adater->effect();
$adater->effect1();


